[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/search*"
  to = "https://express-production.up.railway.app/search:splat"
  status = 200
  force = true

[[redirects]]
  from = "/google/*"
  to = "https://express-production.up.railway.app/google/:splat"
  status = 200
  force = true